server:
  port: 6602
   
eureka:
  instance:
    hostname: localhost
  client:
    # 以下两项一定要是false，表明自己是服务器，而不需要从其他主机发现服务
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #驱逐下线服务 间隔五秒
  server:
    evictionIntervalTimerInMs:5000     
  