server:
  port: 7742
  
# eureka服务地址
eurekaServer: http://localhost:6602/eureka/
# 配置文件路径
configDir: classpath:/config/dev

spring:
  application:
    name: demo-config
  profiles:
    #设置为本地启动的方式，而不是通过git
    active: native
  cloud:
    config:
      server:
        native:
          # 配置文件所在目录，classpath（类路径）和（系统文件路径） file两种
          searchLocations: ${configDir}
              
eureka:
  client:
    serviceUrl:
      defaultZone: ${eurekaServer}
  instance:
    # 实例id
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    # 实例启动页
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true
                                
           
           